version: '3.8'

services:
  app:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    command: npm run dev

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  test:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    command: npm test

  integration-test:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    command: npm run test:integration

volumes:
  redis_data: 