// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhxkjhrmzhnvfnzxdhth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoeGtqaHJtemhudmZuenhkaHRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMTg4OTgsImV4cCI6MjA1ODc5NDg5OH0.LLQuTIfs_nNW0lGhm0VoBtsB2OEzHICu307Vat5wEqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);